### ISSUE TITLE
ICG doesn't compile using clang/llvm 6.0 on the Mac

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#578]
ICG fails to compile with the following error:

```
main.cpp:61:33: error: no viable conversion from '(lambda at main.cpp:61:33)' to 'VersionPrinterTy' (aka 'function<void (llvm::raw_ostream &)>')
    llvm::cl::SetVersionPrinter([] {
                                ^~~~
```
