### ISSUE TITLE
Trick Fails to Build on CentsOS 7

### ISSUE THREAD

**Issue by shaferandrew** [nasa/trick#1538]
The latest Trick fails to build on CentOS 7 (GCC 4.8.5, SWIG 2.0.10)

Building the latest Trick produces the following compilation error:
```bash
make[1]: Entering directory `/home/ajshafer/dev/trick/trick_source/trick_swig'
mkdir swig_Linux_4.8_x86_64
/usr/bin/swig -D_HAVE_GSL -DUSE_ER7_UTILS_INTEGRATORS -I/home/ajshafer/dev/trick/trick_source -I/home/ajshafer/dev/trick/include -I/home/ajshafer/dev/trick -c++ -python -includeall -ignoremissing -w201,362,389,451 -o swig_Linux_4.8_x86_64/sim_services_wrap.cpp -outdir /home/ajshafer/dev/trick/share/trick/swig sim_services.i
/home/ajshafer/dev/trick/include/trick/TCPConnection.hh:21: Error: Syntax error in input(3).
make[1]: *** [swig_Linux_4.8_x86_64/sim_services_wrap.cpp] Error 1
make[1]: Leaving directory `/home/ajshafer/dev/trick/trick_source/trick_swig'
make: *** [/home/ajshafer/dev/trick/trick_source/trick_swig] Error 2
```

I can successfully build Trick 19.6.0 (commit 7e18365), but not HEAD (commit 25d438a) or any commits from c2e42f4 and on.

I can successfully build Trick 19.6.0 and HEAD by using SWIG3 (`./configure --enable-java=no --with-swig=/home/ajshafer/bin/swig3/bin`).

**Comment by dbankieris** [comment]
The problem is the use of `override` in `TCPConnection.hh`. SWIG 2 doesn't handle C++11 features.

**Comment by shaferandrew** [comment]
If SWIG3 is required maybe this issue is actually to update the configure script to report the required SWIG version:
https://github.com/nasa/trick/blob/master/configure#L5746

**Comment by shaferandrew** [comment]
The install guide mentions that SWIG3 is "only required for some unit tests":
https://nasa.github.io/trick/documentation/install_guide/Install-Guide

**Comment by jdeans289** [comment]
We are going to bump the requirement to SWIG 3.0-4.0. 

You should be able to install swig3 on CentOS 7 with `yum -y install swig3`. We will update the configure script and install guide accordingly.

**Comment by jdeans289** [comment]
Configure script has been updated to check for SWIG 3+
