### ISSUE TITLE
LLVM 12.0.0_1 on macOS

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#1152]
Fatal error during Trick build after upgrading from 12.0.0 to 12.0.0_1. Not sure how theres a new bug from a hotfix to the LLVM formula from homebrew, but here we are. This is what is breaking our macOS runner. 
```
/Users/sfennell/trick/include/trick/files_to_ICG.hh:4:10: fatal error: cannot open file '/Users/sfennell/trick/include/trick/trick/reference_frame.h': No such file or directory
#include "trick/reference_frame.h"
         ^
Writing    /Users/sfennell/trick/trick_source/sim_services/include/io_src/io_reference_frame.cpp
make: *** [icg_sim_serv] Segmentation fault: 11
```

**Comment by spfennell** [comment]
Perusing commits to homebrew llvm between April 19th and May 14th (see link below). Seems like they made some changes to how llvm-config behaves. Might be causing our issue. 
https://github.com/Homebrew/homebrew-core/commits/master/Formula/llvm.rb
