### ISSUE TITLE
Build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by iamthad** [nasa/trick#174]
I am encountering the following error when attempting to compile Trick on Ubuntu 16.04
```
object_Linux_5.3_x86_64/ClassVisitor.o: In function `clang::NamedDecl::getNameAsString() const':
/usr/lib/llvm-3.6/include/clang/AST/Decl.h:148: undefined reference to `clang::DeclarationName::getAsString() const'
object_Linux_5.3_x86_64/TypedefVisitor.o: In function `clang::QualType::getAsString(clang::SplitQualType)':
/usr/lib/llvm-3.6/include/clang/AST/Type.h:883: undefined reference to `clang::QualType::getAsString(clang::Type const*, clang::Qualifiers)'
object_Linux_5.3_x86_64/FieldVisitor.o: In function `FieldVisitor::VisitRecordType(clang::RecordType*)':
/home/thadeus/git/trick/trick_source/codegen/Interface_Code_Gen/FieldVisitor.cpp:244: undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
/home/thadeus/git/trick/trick_source/codegen/Interface_Code_Gen/FieldVisitor.cpp:247: undefined reference to `clang::NamedDecl::getQualifiedNameAsString() const'
object_Linux_5.3_x86_64/main.o: In function `main':
/home/thadeus/git/trick/trick_source/codegen/Interface_Code_Gen/main.cpp:107: undefined reference to `llvm::sys::getDefaultTargetTriple()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
makefile:60: recipe for target '/home/thadeus/git/trick/bin/trick-ICG' failed
make[1]: *** [/home/.../git/trick/bin/trick-ICG] Error 1
make[1]: Leaving directory '/home/thadeus/git/trick/trick_source/codegen/Interface_Code_Gen'
Makefile:218: recipe for target '/home/thadeus/git/trick/bin/trick-ICG' failed
make: *** [/home/.../git/trick/bin/trick-ICG] Error 2
```

**Comment by alexlin0** [comment]
I will need to create a virtual machine with Ubuntu 16.04 to test this. I would prefer to wait until Ubuntu 16.04 is closer to release before investigating this.  

Trick is known to compile using clang 3.6 which I see is being used in your printout.

**Comment by alexlin0** [comment]
I downloaded the latest 16.04 beta and tried to compile Trick with it.  I get the same error as you.  The problem appears to be a mixture of some code compiled with gcc 4.x and gcc 5.x.  I tried setting all kinds of compilation and link command line arguments, but in the end I cannot get Trick to compile using the clang/llvm available through apt.  I can however get Trick to compile with clang/llvm downloaded from llvm.org.

I believe that Ubuntu 15.10 has this same problem.

I will update the installation instructions for Ubuntu 16.10 to include the requirement of using clang/llvm from llvm.org.

**Comment by iamthad** [comment]
This appears to be a related issue: https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.4/+bug/1501300

**Comment by alexlin0** [comment]
I believe so.  We have a workaround by not using the clang/llvm downloaded through apt.  I will periodically check to see if the Ubuntu developers resolve this in the future.

**Comment by alexlin0** [comment]
As of now, I have noted on our wiki that for Ubuntu 16.04 and 15.10 users must install clang/llvm by downloading it from llvm.org.  Closing this issue.

**Comment by alexlin0** [comment]
Solved this issue under #259.  Changed the wiki to reflect the fact we no longer need to download clang/llvm from llvm.org.
